Run `go mod tidy` after `go mod edit -replace`
grafana/xk6 pull request #39
Opened 2022-02-16 10:14 UTC by MStoykov

This lets you *not* specify a correctly formatted version for a replace
but let you use branch names or `latest` or nothing (which is `latest`)

2022-02-16 10:17 UTC, MStoykov commented
I did test with a forked extension and with local repo for the main k6 project and both worked fine after the update so hopefully nothing is broken :crossed_fingers:

2022-02-17 10:10 UTC, imiric requested changes
Hhmm this is breaking `xk6 run` from within the xk6-browser repo:

<details>
<summary>Log</summary>

```
$ XK6_BROWSER_LOG=info ~/Projects/grafana/xk6/xk6 run -q examples/226-waitfornavigation-timeout.js
2022/02/17 10:51:26 [INFO] Temporary folder: /tmp/buildenv_2022-02-17-1051.1260111165
2022/02/17 10:51:26 [INFO] Writing main module: /tmp/buildenv_2022-02-17-1051.1260111165/main.go
2022/02/17 10:51:26 [INFO] Initializing Go module
2022/02/17 10:51:26 [INFO] exec (timeout=10s): /home/ivan/.local/go/bin/go mod init k6
go: creating new go.mod: module k6
go: to add module requirements and sums:
        go mod tidy
2022/02/17 10:51:26 [INFO] Replace github.com/grafana/xk6-browser => /home/ivan/Projects/grafana/xk6-browser
2022/02/17 10:51:26 [INFO] exec (timeout=10s): /home/ivan/.local/go/bin/go mod edit -replace github.com/grafana/xk6-browser=/home/ivan/Projects/grafana/xk6-browser
2022/02/17 10:51:26 [INFO] exec (timeout=0s): /home/ivan/.local/go/bin/go mod tidy
go: finding module for package go.k6.io/k6/cmd
go: found github.com/grafana/xk6-browser in github.com/grafana/xk6-browser v0.0.0-00010101000000-000000000000
go: found go.k6.io/k6/cmd in go.k6.io/k6 v0.36.0
go: finding module for package gopkg.in/tomb.v1
go: found gopkg.in/tomb.v1 in gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
k6 imports
        github.com/grafana/xk6-browser imports
        go.k6.io/k6/js/common imports
        github.com/serenize/snaker tested by
        github.com/serenize/snaker.test imports
        github.com/onsi/ginkgo imports
        github.com/onsi/ginkgo/internal/remote imports
        github.com/nxadm/tail imports
        github.com/nxadm/tail/watch imports
        github.com/fsnotify/fsnotify loaded from github.com/fsnotify/fsnotify@v1.4.7,
        but go 1.16 would select v1.4.9

To upgrade to the versions selected by go 1.16:
        go mod tidy -go=1.16 && go mod tidy -go=1.17
If reproducibility with go 1.16 is not needed:
        go mod tidy -compat=1.17
For other options, see:
        https://golang.org/doc/modules/pruning
2022/02/17 10:51:27 [INFO] Cleaning up temporary folder: /tmp/buildenv_2022-02-17-1051.1260111165
2022/02/17 10:51:27 [ERROR] exit status 1
```
</details>

Whereas it works on the current `master`. :confused: I'm on go 1.17.3.

And unrelated to these changes, but I'm actually noticing the same error from [here](https://github.com/grafana/xk6-browser/pull/202) and [here](https://github.com/grafana/xk6-browser/issues/197#issuecomment-1027679691), except when running `xk6 build v0.36.0 --output xk6-browser --with github.com/grafana/xk6-browser@main` (this happens both on the current `xk6` master and on this branch). I wiped my cache just in case... :confused:

And a related comment: could you add some documentation for `--replace` in the README, with some usage examples? Currently it's not clear when it should be used for or what it accomplishes.

2022-02-17 10:18 UTC, MStoykov commented
> And a related comment: could you add some documentation for --replace in the README, with some usage examples? Currently it's not clear when it should be used for or what it accomplishes.

This was done in #33 ?

2022-02-17 10:30 UTC, imiric commented
I know :smile: But coming back to it I'm lapsing on when it's useful, and have to go back and read #32, which probably means the README could explain when it's useful, along with some examples. But you're right, it's unrelated to these changes, we can do that in another PR.

2022-02-17 10:44 UTC, MStoykov commented
It is ... literally what `go mod edit -replace` does ;) So the usefulness and the idea are the same ;)

2022-02-17 10:48 UTC, MStoykov commented
I think this is because of https://go.dev/doc/go1.17#go-command . This does not happen if you run with go1.18 and *is* unrelated to this change AFAIK as well.

I guess we can add `-compat=1.17` and :crossed_fingers: that nobody using 1.16 will run it ?

2022-02-17 10:53 UTC, imiric commented
> It is ... literally what `go mod edit -replace` does ;) So the usefulness and the idea are the same ;)

Sure, but within the context of xk6, which is a wrapper around the go toolchain, we should explain when this is useful (e.g. when you want to replace a dependency of the extension without importing it), instead of "go see what `go mod edit -replace` does".

> I guess we can add `-compat=1.17` and :crossed_fingers: that nobody using 1.16 will run it ?

I wouldn't want to make 1.17 the minimum required version, but if that's the only way of getting this to work, then sure. In that case, let's update the README and `go.mod` to indicate that.

2022-02-17 11:16 UTC, MStoykov commented
This will now error out with 
```
2022/02/17 13:10:37 [INFO] Temporary folder: /tmp/buildenv_2022-02-17-1310.2750852615
2022/02/17 13:10:37 [INFO] Writing main module: /tmp/buildenv_2022-02-17-1310.2750852615/main.go
2022/02/17 13:10:37 [INFO] Initializing Go module
2022/02/17 13:10:37 [INFO] exec (timeout=10s): /home/mstoykov/go/bin/go mod init k6
go: creating new go.mod: module k6
go: to add module requirements and sums:
        go mod tidy
2022/02/17 13:10:37 [INFO] Pinning versions
2022/02/17 13:10:37 [INFO] exec (timeout=0s): /home/mstoykov/go/bin/go mod edit -require go.k6.io/k6@v0.36.0
2022/02/17 13:10:37 [INFO] exec (timeout=0s): /home/mstoykov/go/bin/go mod tidy -compat=1.17
flag provided but not defined: -compat
usage: go mod tidy [-e] [-v]
Run 'go help mod tidy' for details.
2022/02/17 13:10:37 [INFO] Cleaning up temporary folder: /tmp/buildenv_2022-02-17-1310.2750852615
2022/02/17 13:10:37 [FATAL] exit status 2
```

which is not great but I guess it's somewhat better than erroring out for everybody using the latest version (which I would argue are the majority of the people - especially new users). 

Unfortunately capturing the output and checking it will be ... a lot of work which arguably will be outdated in few months when 1.18 is more ubiqutious and we in general no longer support go1.16. Or even depend on 1.18 in k6 or an extension :shrug: .

2022-02-17 14:23 UTC, imiric approved these changes
Thanks, `@<commit-ish>` works properly now :tada:

To avoid that obscure `flag provided but not defined: -compat` error, should we just check `go version` up front and error out with a friendlier message if it's <1.17?

2022-02-17 14:31 UTC, merged