CI: Add build for linux/arm64
grafana/xk6 pull request #66
Opened 2023-05-03 09:27 UTC by iainlane

This builds and pushes a multi-arch Docker manifest for amd64 and arm64.

We use Docker's provided action to do this using qemu emulation.

Split the build/test of the `xk6` binary out to a separate job too, so that can also be run on arm64.

2023-05-04 17:54 UTC, iainlane commented
Example runs where I had hacked the action to work on pushes to `iainlane/*`:

  * [`master`](https://github.com/iainlane/xk6/actions/runs/4885649492)
  * [tag](https://github.com/iainlane/xk6/actions/runs/4885677479) (gets `latest` and `1.0.0`, the `v` is dropped)
  * [rc](https://github.com/iainlane/xk6/actions/runs/4885677485) (gets `1.0.0-rc.1` but **not** `latest`)

Expand "Set up tags" -> "Docker tags" to see what each run tagged.

See the resulting pushed container images:

  * [GHCR](https://github.com/iainlane/xk6/pkgs/container/xk6)
  * [Docker Hub](https://hub.docker.com/r/iainlane/xk6/tags)

2023-05-09 10:31 UTC, imiric requested changes
Hey, thanks for this! :bow:

Using actions instead of doing this manually certainly helps, though I liked the clarity of raw commands :smile:

The main blocker for me would be figuring out how to do the build-test-push workflow, instead of building and pushing in the same step.

2023-05-09 10:31 UTC, imiric commented on .github/workflows/release.yml
> +    runs-on: ubuntu-latest
Let's add a dependency on `binary` here, to avoid building the Docker image if there's an issue with the binary.

```suggestion
    runs-on: ubuntu-latest
    needs: [binary]
```

2023-05-09 10:31 UTC, imiric commented on .github/workflows/release.yml
> +          tags: ${{ steps.meta.outputs.tags }}
We should have conditionals on all of these steps, and maybe on the overall job, to only do this on `master` or tagged commits.

2023-05-09 10:31 UTC, imiric commented on .github/workflows/release.yml
> +        uses: docker/setup-qemu-action@v2
Is QEMU needed for `buildx` and the ARM build? Let's add a comment here to explain this.

2023-05-09 10:31 UTC, imiric commented on .github/workflows/release.yml
> -        run: docker build -t "$IMAGE_REPOSITORY" .
Without building the image here, the image used below to build k6 would be `grafana/xk6:latest`. So there's not much point in always testing that particular image.

What we want to do is to test the same image we've just built, _before_ we push it to the registries. From my limited experience with `docker buildx`, that's apparently not possible, since it only exposes a `--push` flag to build and push with the same command. This is probably why the action is named `docker/build-push-action`, since it's not possible to split these two steps.

It also doesn't seem possible to run `docker buildx` without `--push`, and then run `docker push`, since that only pushes the amd64 image, and not the arm64 one. This is the behavior we've noticed in https://github.com/grafana/k6/pull/3015.

If you have any ideas for how to structure a multi-arch workflow in a way that we can build, test and push, in that order, we'd appreciate it.

2023-05-09 10:57 UTC, iainlane commented on .github/workflows/release.yml
> +      - name: Set up QEMU
```suggestion
      - name: Set up QEMU to build the arm64 binary
```

2023-05-09 10:57 UTC, iainlane commented on .github/workflows/release.yml
> -        run: docker build -t "$IMAGE_REPOSITORY" .
I tried a bit when making the PR - you can `load` the image into the docker daemon so it's available in later steps, but this doesn't work with multiarch manifests for some annoying reason (you get an error). Didn't seem to be a workaround for that from the brief searching I did.

What about running the tests from the `Dockerfile` so building is actually building + testing? Would that be okay?

Alternatively you could probably apply the matrix to the Docker builds themselves. That is: build the images in separate jobs, push `foo-ARCH` tags to the registry, then have a final job which is dependent on all of the builds succeeding which builds and pushes the manifest. It's a bit more work and I don't know when I'd have time to come back and do that if we decided to go down that route, though.

2023-05-09 10:57 UTC, iainlane commented on .github/workflows/release.yml
> +          tags: ${{ steps.meta.outputs.tags }}
The overall workflow has a condition like that, is that enough?

2023-05-09 10:58 UTC, iainlane commented on .github/workflows/release.yml
> +        uses: docker/setup-qemu-action@v2
I renamed the step to be more explicit, could you check?

2023-05-09 13:06 UTC, imiric commented on .github/workflows/release.yml
> -        run: docker build -t "$IMAGE_REPOSITORY" .
Both of your suggestions are interesting, thanks.

> What about running the tests from the `Dockerfile` so building is actually building + testing? Would that be okay?

Ideally, we'd want to test the exact image that users will use, but this could be a reasonable alternative. We just need to make sure to do the test in the first build stage, so that the cached packages used in the test are not part of the final image.

> Alternatively you could probably apply the matrix to the Docker builds themselves. That is: build the images in separate jobs, push `foo-ARCH` tags to the registry, then have a final job which is dependent on all of the builds succeeding which builds and pushes the manifest. It's a bit more work and I don't know when I'd have time to come back and do that if we decided to go down that route, though.

True, this could be an option as well. I think this approach is cleaner and would be our preferred solution, but you're right that it's more complicated to setup.

Practically speaking, either approach would be transparent for users, so if you're short on time, let's go with the first approach for now. The benefit of having ARM images outweighs any potential problems, and I'll create an issue to implement the second approach, which we can address eventually.

Thanks again!

2023-05-09 13:14 UTC, imiric commented on .github/workflows/release.yml
> +          tags: ${{ steps.meta.outputs.tags }}
Ah, right, I missed it. So the conditionals on the `Log into` steps can be removed, right?

2024-07-04 11:38 UTC, closed without merging

2024-07-04 11:39 UTC, pablochacin commented
Closing due to staleness. If this is required we need to open a new PR aligned with the current vision of the tooling ecosystem